# Generated by Django 4.0 on 2022-01-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='network.user'),
        ),
    ]
